// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppPractise.Dal;

#nullable disable

namespace WebAppPractise.Migrations
{
    [DbContext(typeof(VideoContextDb))]
    [Migration("20251025063545_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAppPractise.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Developer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Developer = "Insomic",
                            Platform = "PS5",
                            Publisher = "sony",
                            Title = "SpiderMan"
                        },
                        new
                        {
                            Id = 2,
                            Developer = "Insomic Inc",
                            Platform = "PS3",
                            Publisher = "Nintendo",
                            Title = "SpiderMan-2"
                        },
                        new
                        {
                            Id = 3,
                            Developer = "soCD Project",
                            Platform = "CyberPunk",
                            Publisher = "soCD Project",
                            Title = "The Brothers"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
